data:
  dataset_dir: "/workspaces/vast-gorilla/gorillawatch/data3/stratified_open_split_NEW/spac23+24-body_face-squared-deduplicated"
  #dataset_dir: "/workspaces/vast-gorilla/gorillawatch/data/berlin_zoo_dataset/squared_renamed/body"
  batch_size: 32
  base_mask_dir: "/workspaces/vast-gorilla/gorillawatch/iven_thesis/masks"
  output_base_dir: "/workspaces/vast-gorilla/gorillawatch/iven_thesis/seg_analysis"
  analysis_split: "test"

  zoo_subsample_fraction: 0.2
  coco_json_path: "/workspaces/vast-gorilla/gorillawatch/data/berlin_zoo_dataset/squared_renamed/dataset.json" 
  zoo_video_dir: "/workspaces/vast-gorilla/gorillawatch/data/berlin_zoo_dataset/videos"

seed: 161

db:
  db_schema: "public"
  feature_type: "body"

eval:
  patches_per_step: 50
  baseline_value: "mean" #mean or black

knn:
  distance_metric: "euclidean" # "cosine" or "euclidean"
  k: 5
  db_embeddings_dir: "/workspaces/vast-gorilla/gorillawatch/iven_thesis/knn_db"

model:
  img_size: 518
  backbone: "vit_giant_patch14_dinov2.lvd142m"
  embedding_dim: 256
  patch_size: 14
  model_dtype: "float32"
  bp_transforms: True # Should the transforms from the previous BP's work be used or the transforms that come from timm

plots:
  red: [162, 41, 64]
  orange: [206, 104, 45]
  yellow: [236, 172, 61]
  gray: [172, 175, 178]

wandb:
  project: "bachelor_thesis"
  entity: "gorillawatch"

lrp:
  mode: "soft_knn_margin_all"
  distance_metric: "cosine" # so far, all of the scores work with cosine similarity
  cross_encounter: True
  db_relevances_dir: "/workspaces/vast-gorilla/gorillawatch/iven_thesis/relevance_db"
  eval_db: "all" # "all" (for train + test) or "test"


sweep:
  sweep_evaluation: "accuracy" # "accuracy" or "proxy_score" to evaluate over the proxy score itself. Rather use accuracy
  distance_metrics: ["cosine"]
  holdout_percentage: 0.2
  top_k_for_val: 10
  acceptable_drop_percent: 35.0
  queries_per_class: 4



